### ISSUE TITLE
Plugin Support version 3

### ISSUE THREAD

**Issue by cello86** [coreruleset/dos-protection-plugin-modsecurity-v2#7]
Hi we noticed that this plugin is supported only for v2 for some problem with expirevar support in the newer version of mod_security.
The support for expirevar on newer version has been released into 3.0.11 version.

Could you confirm if this plugin can be compliant with the branch 3 of mod_security?

Thanks,
Marcello

**Comment by theseion** [comment]
This plugin does not work yet (as noted [here](https://github.com/coreruleset/plugin-registry), we did not officially release it yet). As for v3, yes, this plugin would now work for both versions since the expirevar issue has been fixed in v3.
